-- Curated description rewrites for locations 217–317 (the 101 imported 2026-05-25)
-- Replaces templated "Restaurant in X." style copy with more evocative, use-case-aware text.
-- Safe to re-run: idempotent on description content.

update locations set
  description = case id
    when 217 then 'Sleek modern dining in Modi''in — a confident pick when you want the night to feel a step up from casual.'
    when 218 then 'Late-night cocktails and a buzzing crowd. Better as a second-stop than a first-meeting.'
    when 219 then 'Familiar Italian comfort in Modi''in — pasta, pizza, easy conversation. Low pressure, high success rate.'
    when 220 then 'Irish-pub energy in Modi''in. Loud, lively, good for unwinding once you''re past the awkward first hello.'
    when 221 then 'Small boutique winery near Jerusalem. The kind of unexpected detour that turns a date into a story.'
    when 222 then 'Trendy and stylish — Tel Aviv at its most photogenic. Dress nicely; this one is for impressing.'
    when 223 then 'Restaurant inside the Setai Hotel in Jaffa. Restrained luxury and one of the city''s most romantic settings.'
    when 224 then 'On Rothschild Boulevard — modern Israeli plates and a polished room. Strong third-date energy.'
    when 225 then 'Eyal Shani''s flagship — bold flavors, raw vegetables, a room that announces you''re trying.'
    when 226 then 'Seafood at the Jaffa port with sea air and golden hour. One of the most cinematic dinners in the country.'
    when 227 then 'Tel Aviv neighborhood spot — relaxed, dependable, and easy to suggest without overthinking it.'
    when 228 then 'Mediterranean small plates in Tel Aviv. Sharing-style menu does half the conversation work for you.'
    when 229 then 'Polished Tel Aviv dining that holds the room. Works for a celebration or a serious-stage date.'
    when 230 then 'Loud, fun, drinks-forward. Skip this for first dates — it shines once you''re comfortable.'
    when 231 then 'Quiet French dining in Tel Aviv. Candles, low conversation, the kind of dinner that earns a second one.'
    when 232 then 'Hidden courtyard wine bar — intimate, slow-paced, designed for talking past dessert.'
    when 233 then 'Sushi and wine on Tel Aviv''s scene. Counter seats are the move — side-by-side beats face-to-face here.'
    when 234 then 'Reliable Rishon spot when you want a real meal without overthinking dress code or budget.'
    when 235 then 'Italian standards done well in Rishon. The safe-but-good choice when you don''t want to gamble.'
    when 236 then 'Italian comfort food in Rishon — the kind of menu where you''ll both find something you love.'
    when 237 then 'The Rishon LeZion branch of the Luciana family — same warm Italian formula, easier to get into.'
    when 238 then 'Bar-restaurant in Rishon with a drinks-first vibe. Great for an unstructured Thursday night.'
    when 239 then 'Sushi in Rishon — clean, modern, and consistent. A solid mid-tier choice without the Tel Aviv markup.'
    when 240 then 'Trendy Rishon spot with a confident menu. Newer face on the scene, worth a look.'
    when 241 then 'Mediterranean dining in Rishon. The kind of place that feels grown-up without being stiff.'
    when 242 then 'All-day café in Rishon — breakfast, brunch, slow afternoons. Easy first meet without dinner pressure.'
    when 243 then 'Patrick''s — the Petach Tikva branch of the bar-restaurant chain. Beers, burgers, friend-energy. Light date.'
    when 244 then 'Memphis — American smokehouse vibes in Tel Aviv. Big portions, casual, leans group-night.'
    when 245 then 'Jem''s Beer Factory in Petach Tikva. Bar food, on-tap beer, low-pressure energy.'
    when 246 then 'The Or Yehuda branch of Café Lyon. Classic café formula — works for both breakfast and an afternoon pause.'
    when 247 then 'Bukharan cuisine in Or Yehuda — plov, lagman, a meal that doubles as a cultural conversation.'
    when 248 then 'Serious BBQ smokehouse in Petach Tikva — low-and-slow brisket, meat-lover''s pick.'
    when 249 then 'A pretty garden café — the kind of place where the setting does emotional work for you.'
    when 250 then 'Jerusalem café-bar with a youthful crowd. Good for the in-between hour — late lunch, early drinks.'
    when 251 then 'Honest Italian pasta in Jerusalem. Comforting, fairly priced, and unlikely to disappoint.'
    when 252 then 'Café tucked into San Simon Park — coffee with grass and breathing room. Soft first-date energy.'
    when 253 then 'A café in Ein Hemed forest. Trees, tables outside, the wow of "I didn''t know this existed."'
    when 254 then 'Italian in Hod HaSharon — quiet street, real cooking, a dependable choice north of the city.'
    when 255 then 'Charcoal-grilled meats, Turkish style. Generous, social, and unmistakably a meal worth showing up hungry for.'
    when 256 then 'Village-feel meat house in Or Yehuda — old-school grill, no pretense, big flavors.'
    when 257 then 'Or Yehuda institution. Grills, salads, the kind of place locals quietly love.'
    when 258 then 'Warm neighborhood dining in Or Yehuda — comfortable, generous, easy to recommend.'
    when 259 then 'Beachfront in Caesarea — sunset, sea breeze, plates worth lingering over. A statement choice.'
    when 260 then 'At the Caesarea port — water views, slow service in the best sense, and a sense of occasion.'
    when 261 then 'Modern Petach Tikva dining — chef-driven plates without the Tel Aviv attitude.'
    when 262 then 'A bakery-café with serious bread game. Petach Tikva''s pick for a relaxed daytime meet.'
    when 263 then 'Easygoing café in Petach Tikva — the kind of place a casual coffee can stretch into two hours.'
    when 264 then 'Petach Tikva café with quiet corners. Built for conversation, not background music.'
    when 265 then 'Sha''arei Tikva café — small, warm, and just out of the city enough to feel like a small escape.'
    when 266 then 'Sweet-leaning café in Petach Tikva. Lighter mood, lower stakes — good first-meet territory.'
    when 267 then 'Asian-fusion in Petach Tikva — bao, ramen, the kind of menu that makes the order itself a conversation.'
    when 268 then 'Italian in Petach Tikva with proper attention to detail. Polished without being formal.'
    when 269 then 'Wine bar in Petach Tikva. Smaller pours, longer conversations — closer to second-date than first-coffee.'
    when 270 then 'Tapas-style sharing menu in Petach Tikva. The food does the small-talk for you.'
    when 271 then 'The Petach Tikva branch of Bleecker Bakery — pastries that punch above their postcode.'
    when 272 then 'A laid-back café in Petach Tikva. Brunch crowd, friendly service, low decision-fatigue.'
    when 273 then 'Plant-forward café in Petach Tikva — works whether one of you is vegetarian or just curious.'
    when 274 then 'Italian in Petach Tikva — generous portions, family feel, no surprises in the best way.'
    when 275 then 'A real brasserie in Petach Tikva — steak frites energy, white tablecloths, dim light. Bring intention.'
    when 276 then 'Modern dining in Ramat Gan. The Bursa-side crowd — confident food, confident room.'
    when 277 then 'Ramat Gan chef restaurant that takes itself seriously without overdoing it.'
    when 278 then 'Quiet Ramat Gan café — slow mornings, real coffee, no rush to clear your table.'
    when 279 then 'Mediterranean dining in Ramat Gan. The kind of place that feels just-right for a midweek date.'
    when 280 then 'Tiny coffee cart in Savyon. Worth it for the surprise factor alone — date as a small adventure.'
    when 281 then 'Bar-restaurant in Holon with proper kitchen and a real bar. Built for a long, unhurried evening.'
    when 282 then 'Bat Yam dining with a chef-driven menu — bigger flavors than the address suggests.'
    when 283 then 'Chef restaurant in Rehovot — ambitious cooking outside the usual Tel Aviv circuit. Worth the drive.'
    when 284 then 'A café inside a working plant nursery in Be''er Ya''akov. Greenhouse light, no city noise, easy to relax.'
    when 285 then 'A farm bakery-café in Moshav Chemed. Fresh bread, big tables, country pace.'
    when 286 then 'Beach café in Shfayim — sand-and-sea backdrop, especially good at off-peak hours.'
    when 287 then 'A café in Ariel Sharon Park — grass, open sky, room to walk before or after.'
    when 288 then 'Coffee cart in Moshav Shuva. A small detour that signals effort without trying too hard.'
    when 289 then 'Pizza food truck in Ganei Tikva. Outdoor seating, low pressure, easy yes.'
    when 290 then 'Coffee cart on a quiet street in Magshimim — a 20-minute coffee stop that turns into 90.'
    when 291 then 'Yehud café with a regulars'' feel. The neighborhood spot that quietly wins by showing up every day.'
    when 292 then 'A countryside café in Moshav Mazor — slow service, slower conversation, exactly the point.'
    when 293 then 'A coffee cart hidden in Hagor. The drive there is half the date.'
    when 294 then 'Beach café at Chof Ne''urim. Wood, sand, low sun — one of the prettier coastal mornings around.'
    when 295 then 'A neighborhood café in Tzofit. Small, calm, and easy to settle into.'
    when 296 then 'Café in Chibat Tzion — small-moshav energy and a no-rush attitude.'
    when 297 then 'Local Tzur Yigal café with a regulars'' vibe. Tucked enough to feel like your private find.'
    when 298 then 'Garden café in Kfar Yona — outdoor seating, kids-and-couples mix, daytime energy.'
    when 299 then 'Elyakhin neighborhood café. Honest food, fair prices, the kind of place locals defend.'
    when 300 then 'A café in the Ganei Tal community — slow, southern, exactly off the beaten path.'
    when 301 then 'Ganei Tal café — community-feel mornings, the opposite of city rush.'
    when 302 then 'Farmer''s market in Moshav Matzliach. Walk-and-talk date with samples — works better than it sounds.'
    when 303 then 'Moshav Beniyah café — easy detour for an afternoon coffee that doubles as a small adventure.'
    when 304 then 'A farmhouse café at Meshek Levi. The setting is the whole pitch — and it''s a good one.'
    when 305 then 'Binyamina café with character. The neighborhood-favorite kind, not the Instagram kind.'
    when 306 then 'A café in Ein Carmel — moshav-quiet, slow service, real bread.'
    when 307 then 'Italian food truck in Megadim. Unexpected pizza-and-pasta stop on the coastal road.'
    when 308 then 'Restaurant at Ein HaNatziv, in the Beit She''an Valley — countryside dining that earns the trip.'
    when 309 then 'Galilee café in Moshav HaZore''im. Make it part of a northern day-trip and it goes from coffee to memorable.'
    when 310 then 'Food truck in Ora, in the hills outside Jerusalem. Pair it with a short hike for an effortless half-day.'
    when 311 then 'Farm café in Sde Moshe — open fields, southern light, slow Saturday afternoons.'
    when 312 then 'A café on a working farm in Tkuma. Big skies, no rush, story-worthy.'
    when 313 then 'Moshav Brachia café — small, kind, and a real detour from the usual.'
    when 314 then 'A café next to the stream in Ein Tzurim. The sound of water does most of the work.'
    when 315 then 'Café at Khan Merhav Am — desert quiet, big sky, a date that doubles as a small pilgrimage.'
    when 316 then 'A café in the cliffs above the Dead Sea. The view alone makes this a memorable stop.'
    when 317 then 'A village café in Kfar HaRo''eh — old-fashioned in the best way, and very easy to linger at.'
    else description
  end,
  description_he = case id
    when 217 then 'מסעדה מודרנית ואלגנטית במודיעין — בחירה בטוחה לערב שמרגיש קצת יותר מ"סתם".'
    when 218 then 'קוקטיילים וזמזום של קהל לתוך הלילה. עדיף כעצירה שנייה, לא ראשונה.'
    when 219 then 'איטלקיה מוכרת ונעימה במודיעין — פסטה, פיצה, שיחה קלה. סיכויי הצלחה גבוהים.'
    when 220 then 'אווירת פאב אירי במודיעין. רועש, חי, וטוב כשאתם כבר רגועים.'
    when 221 then 'יקב בוטיק קטן ליד ירושלים. סטייה לא צפויה שהופכת דייט לסיפור.'
    when 222 then 'אופנתי ומעוצב — תל אביב במיטבה. תתלבשו יפה, זה דייט להרשים בו.'
    when 223 then 'מסעדה במלון סטאי ביפו. יוקרה מאופקת ואחת הסביבות הכי רומנטיות בעיר.'
    when 224 then 'על שדרות רוטשילד — מטבח ישראלי מודרני וחלל מטופח. אנרגיית דייט שלישי חזקה.'
    when 225 then 'המסעדה הדגלית של אייל שני — טעמים נועזים וחלל שאומר שאתם משקיעים.'
    when 226 then 'מסעדת דגים בנמל יפו עם אוויר ים ושקיעה. אחת מארוחות הערב הקולנועיות בארץ.'
    when 227 then 'מסעדה שכונתית בתל אביב — רגועה, אמינה, קלה להציע בלי לחץ.'
    when 228 then 'מנות שיתופיות ים-תיכוניות בתל אביב. תפריט שעושה חצי מהשיחה בשבילכם.'
    when 229 then 'מסעדה מטופחת בתל אביב שמחזיקה את החלל. מתאימה לחגיגה או לדייט רציני.'
    when 230 then 'רועש, כיפי, ממוקד-משקאות. דלגו בדייט ראשון — הוא בוהק כשכבר מכירים.'
    when 231 then 'מסעדה צרפתית שקטה בתל אביב. נרות, שיחה נמוכה, ארוחה שמזכה בעוד אחת.'
    when 232 then 'בר יין נסתר בחצר — אינטימי, איטי, בנוי לשיחה שנמשכת אחרי הקינוח.'
    when 233 then 'סושי ויין על מפת תל אביב. הכי טוב לשבת ליד הבר — לצד-לצד מנצח פנים-מול-פנים.'
    when 234 then 'מסעדה אמינה בראשון לציון — ארוחה אמיתית בלי כאב ראש של קוד לבוש או תקציב.'
    when 235 then 'איטלקיה קלאסית בראשון, עשויה היטב. בחירה בטוחה כשלא רוצים להמר.'
    when 236 then 'אוכל איטלקי מנחם בראשון — תפריט שבו שניכם תמצאו משהו שאתם אוהבים.'
    when 237 then 'הסניף הראשון-לציוני של משפחת לוצ׳אנה — אותה איטלקיה חמה, רק קלה יותר לתפוס בה מקום.'
    when 238 then 'בר-מסעדה בראשון עם וייב של משקאות. מצוין לערב חמישי לא מתוכנן.'
    when 239 then 'סושי בראשון — נקי, מודרני, עקבי. מקום מצוין באמצע הסקאלה בלי המחירים של תל אביב.'
    when 240 then 'מסעדה חדשה ואופנתית בראשון. תפריט בטוח בעצמו, שווה בדיקה.'
    when 241 then 'אוכל ים-תיכוני בראשון. מקום שמרגיש "בוגר" בלי להיות נוקשה.'
    when 242 then 'בית קפה לכל היום בראשון — בוקר, ברנץ׳, אחרי-צהריים שקטים. מפגש ראשון בלי לחץ ארוחת ערב.'
    when 243 then 'פטריקס — סניף פתח תקווה של רשת הבר-מסעדה. בירה, המבורגרים, אנרגיית חברים. דייט קליל.'
    when 244 then 'ממפיס — מעשנה אמריקאית בתל אביב. מנות גדולות, קז׳ואל, נוטה לערב חברים.'
    when 245 then 'ג׳מס — מבשלת בירה ומסעדה בפתח תקווה. אוכל בר, ברז פתוח, בלי לחץ.'
    when 246 then 'סניף אור יהודה של קפה ליון. נוסחת בית קפה קלאסית — עובדת גם לבוקר וגם לעצירה אחר־הצהריים.'
    when 247 then 'מטבח בוכרי באור יהודה — פלוב, לגמן, ארוחה שגם משיחת תרבות.'
    when 248 then 'מעשנה רצינית בפתח תקווה — בריסקט איטי, חלום של חובבי בשרים.'
    when 249 then 'בית קפה עם גן יפה — סביבה שעושה עבודה רגשית בשבילכם.'
    when 250 then 'בית קפה-בר בירושלים עם קהל צעיר. טוב לשעה הביניים — צהריים מאוחר, אחר־צהריים מוקדם.'
    when 251 then 'פסטה איטלקית כנה בירושלים. מנחם, מתומחר הוגן, קשה לאכזב.'
    when 252 then 'בית קפה בפארק סן סימון — קפה עם דשא ואוויר. אנרגיית דייט ראשון רכה.'
    when 253 then 'בית קפה ביער עין חמד. עצים, שולחנות בחוץ, ההפתעה של "לא ידעתי שזה קיים".'
    when 254 then 'איטלקיה בהוד השרון — רחוב שקט, בישול אמיתי, בחירה אמינה מצפון לעיר.'
    when 255 then 'בשרים על האש בסגנון טורקי. נדיב, חברתי, ארוחה ששווה להגיע אליה רעבים.'
    when 256 then 'בית בשרים באור יהודה עם וייב כפרי — גריל של פעם, בלי יומרה, טעמים גדולים.'
    when 257 then 'מוסד באור יהודה. גרילים, סלטים, מקום שהמקומיים אוהבים בשקט.'
    when 258 then 'מסעדה שכונתית חמימה באור יהודה — נוחה, נדיבה, קלה להמליץ עליה.'
    when 259 then 'מסעדת חוף בקיסריה — שקיעה, רוח ים, מנות ששווה לנשנש לאורך זמן. בחירה מצהירה.'
    when 260 then 'בנמל קיסריה — נוף לים, שירות איטי במובן הטוב, ותחושה של אירוע.'
    when 261 then 'מטבח שף בפתח תקווה — מנות מודרניות בלי האטיטיוד התל-אביבי.'
    when 262 then 'מאפייה-בית קפה עם לחם רציני. הבחירה של פתח תקווה לפגישה רגועה ביום.'
    when 263 then 'בית קפה נינוח בפתח תקווה — מקום שקפה קליל בו נמתח לשעתיים.'
    when 264 then 'בית קפה בפתח תקווה עם פינות שקטות. בנוי לשיחה, לא לרעש רקע.'
    when 265 then 'בית קפה בשערי תקווה — קטן, חם, ומספיק מחוץ לעיר כדי להרגיש בריחה קטנה.'
    when 266 then 'בית קפה עם נטייה למתוק בפתח תקווה. מצב רוח קליל, סיכון נמוך — שטח טוב לפגישה ראשונה.'
    when 267 then 'אסיאתי-פיוז׳ן בפתח תקווה — באו, ראמן, תפריט שההזמנה עצמה בו שיחה.'
    when 268 then 'איטלקיה בפתח תקווה עם תשומת לב לפרטים. מטופחת בלי להיות רשמית.'
    when 269 then 'בר יין בפתח תקווה. כוסות קטנות יותר, שיחות ארוכות יותר — קרוב יותר לדייט שני מאשר לקפה ראשון.'
    when 270 then 'תפריט שיתופי בסגנון טאפאס בפתח תקווה. האוכל עושה את הסמול-טוק במקומכם.'
    when 271 then 'הסניף של בליקר בייקרי בפתח תקווה — מאפים שמכים מעל ליגה שלהם.'
    when 272 then 'בית קפה רגוע בפתח תקווה. קהל ברנץ׳, שירות נחמד, בלי עומס החלטות.'
    when 273 then 'בית קפה צמחי בפתח תקווה — מתאים גם אם אחד מכם צמחוני וגם אם רק סקרן.'
    when 274 then 'איטלקיה בפתח תקווה — מנות נדיבות, וייב משפחתי, בלי הפתעות במובן הטוב.'
    when 275 then 'בראסרי צרפתי אמיתי בפתח תקווה — אנרגיית סטייק פריט, מפות לבנות, אור עמום. בואו עם כוונה.'
    when 276 then 'מסעדה מודרנית ברמת גן — קהל הבורסה, אוכל בטוח בעצמו וחלל בטוח בעצמו.'
    when 277 then 'מסעדת שף ברמת גן שמתייחסת לעצמה ברצינות בלי להגזים.'
    when 278 then 'בית קפה שקט ברמת גן — בקרים איטיים, קפה אמיתי, בלי לחץ לפנות את השולחן.'
    when 279 then 'מטבח ים-תיכוני ברמת גן. מקום שמרגיש "בדיוק מתאים" לדייט אמצע-שבוע.'
    when 280 then 'עגלת קפה זעירה בסביון. שווה רק בגלל אפקט ההפתעה — דייט כהרפתקה קטנה.'
    when 281 then 'בר-מסעדה בחולון עם מטבח רציני ובר אמיתי. בנוי לערב ארוך ונינוח.'
    when 282 then 'מסעדה בבת ים עם תפריט שף — טעמים גדולים יותר ממה שהכתובת מבטיחה.'
    when 283 then 'מסעדת שף ברחובות — בישול שאפתני מחוץ למסלול תל אביב. שווה את הנסיעה.'
    when 284 then 'בית קפה בתוך משתלה פעילה בבאר יעקב. אור של חממה, בלי רעש עיר, קל להירגע.'
    when 285 then 'מאפייה-בית קפה במשק חקלאי במושב חמד. לחם טרי, שולחנות גדולים, קצב של כפר.'
    when 286 then 'בית קפה לחוף הים בשפיים — חול וים ברקע, מצוין במיוחד בשעות שקטות.'
    when 287 then 'בית קפה בפארק אריאל שרון — דשא, שמיים פתוחים, מקום לטיול לפני או אחרי.'
    when 288 then 'עגלת קפה במושב שובה. סטייה קטנה שמשדרת השקעה בלי להתאמץ יותר מדי.'
    when 289 then 'פוד טראק של פיצה בגני תקווה. ישיבה בחוץ, בלי לחץ, "כן" קל.'
    when 290 then 'עגלת קפה ברחוב שקט במגשימים — עצירה של 20 דקות שמתפתחת ל-90.'
    when 291 then 'בית קפה ביהוד עם תחושת רגילים. הספוט השכונתי שמנצח בעקביות.'
    when 292 then 'בית קפה כפרי במושב מזור — שירות איטי, שיחה איטית עוד יותר, וזו בדיוק הנקודה.'
    when 293 then 'עגלת קפה נסתרת בחגור. הנסיעה לשם היא חצי מהדייט.'
    when 294 then 'בית קפה בחוף נעורים. עץ, חול, אור נמוך — אחד הבקרים היפים בחוף.'
    when 295 then 'בית קפה שכונתי בצופית. קטן, רגוע, קל להתבסס בו.'
    when 296 then 'בית קפה בחיבת ציון — אנרגיית מושב קטן וגישה של "אין למה למהר".'
    when 297 then 'בית קפה מקומי בצור יגאל. מספיק נסתר כדי להרגיש כמו הגילוי הפרטי שלכם.'
    when 298 then 'בית קפה עם גן בכפר יונה — ישיבה בחוץ, תמהיל זוגות וילדים, אנרגיית יום.'
    when 299 then 'בית קפה שכונתי באליכין. אוכל ישר, מחירים הוגנים, מקום שהמקומיים מגנים עליו.'
    when 300 then 'בית קפה בקהילת גני טל — איטי, דרומי, בדיוק מחוץ למסלול.'
    when 301 then 'בית קפה בגני טל — בקרי תחושת קהילה, ההפך מקצב העיר.'
    when 302 then 'שוק חקלאי במושב מצליח. דייט של הליכה ושיחה עם טעימות — עובד טוב יותר משזה נשמע.'
    when 303 then 'בית קפה במושב בניה — סטייה קלה לקפה של אחה״צ שהופך לחוויה קטנה.'
    when 304 then 'בית קפה כפרי במשק לוי. הסביבה היא כל הסיפור — וסיפור טוב.'
    when 305 then 'בית קפה בבנימינה עם אופי. מהסוג של המועדף השכונתי, לא של האינסטגרם.'
    when 306 then 'בית קפה בעין כרמל — שקט של מושב, שירות איטי, לחם אמיתי.'
    when 307 then 'פוד טראק איטלקי במגדים. עצירה של פיצה-ופסטה לא צפויה בדרך החוף.'
    when 308 then 'מסעדה בעין הנצי״ב, בעמק המעיינות — מטבח כפרי ששווה את הנסיעה.'
    when 309 then 'בית קפה גליליי במושב הזורעים. שלבו אותו ביום צפוני — מקפה הופך לזיכרון.'
    when 310 then 'פוד טראק באורה, בהרי ירושלים. שלבו אותו עם טיול קצר — חצי יום בלי מאמץ.'
    when 311 then 'בית קפה בחווה בשדה משה — שדות פתוחים, אור דרומי, אחר־צהריים שבת איטיים.'
    when 312 then 'בית קפה במשק פעיל בתקומה. שמיים גדולים, בלי לחץ, סיפור לספר.'
    when 313 then 'בית קפה במושב ברכיה — קטן, נחמד, סטייה אמיתית מהשגרה.'
    when 314 then 'בית קפה ליד הנחל בעין צורים. צליל המים עושה את רוב העבודה.'
    when 315 then 'בית קפה בחאן מרחב עם — שקט מדברי, שמיים גדולים, דייט עם נופך עלייה לרגל קטנה.'
    when 316 then 'בית קפה בצוקים מעל ים המלח. הנוף לבדו הופך את העצירה לבלתי נשכחת.'
    when 317 then 'בית קפה כפרי בכפר הרא״ה — מהסוג של פעם, וקל להישאר בו לזמן ארוך.'
    else description_he
  end
where id between 217 and 317;

-- Refresh missing_fields and confidence for the rewritten rows
update locations
set missing_fields = array_remove(missing_fields, 'description_weak'),
    confidence_score = least(100, greatest(0,
      40
      + case when lat is not null and lng is not null then 15 else 0 end
      + case when image_url is not null and image_url <> '' then 15 else 0 end
      + case when google_rating is not null then 10 else 0 end
      + case when description is not null and length(description) >= 60 then 10 else 0 end
      + case when slug is not null then 5 else 0 end
      + case when name_he is not null and city_he is not null then 5 else 0 end
      - case when business_status = 'CLOSED_PERMANENTLY' then 40 else 0 end
    ))
where id between 217 and 317;
