-- ─────────────────────────────────────────────
-- HaMakom — Supabase schema
-- Run once in the Supabase SQL editor or via psql
-- ─────────────────────────────────────────────

-- ── Tables ────────────────────────────────────

create table if not exists locations (
  id          bigint generated by default as identity primary key,
  name        text not null,
  name_he     text,
  city        text not null,
  city_he     text,
  category    text not null,
  occasion    text[]    default '{}',
  price       int       default 2,
  date_stage  int[]     default '{}',
  description text,
  description_he text,
  maps_query  text,
  kashrus     text,
  featured    boolean   default false,
  status      text      default 'approved',
  created_at  timestamptz default now()
);

create table if not exists pending_submissions (
  id           bigint generated by default as identity primary key,
  name         text not null,
  city         text not null,
  category     text not null,
  kashrus      text,
  why          text,
  whatsapp     text,
  date_stage   int[],
  price        int  default 2,
  status       text default 'pending',
  submitted_at timestamptz default now()
);

-- Stores quiz answers per authenticated user (one row per quiz attempt)
create table if not exists user_quiz_results (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references auth.users(id) on delete cascade,
  answers    jsonb not null,
  created_at timestamptz default now()
);

alter table user_quiz_results enable row level security;

create policy "users_own_quiz_results"
  on user_quiz_results for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ── Row-Level Security ────────────────────────

alter table locations          enable row level security;
alter table pending_submissions enable row level security;

-- locations: public can read approved; anyone (anon) can insert/update for admin ops
create policy "public_read_approved"
  on locations for select
  using (status = 'approved');

create policy "anon_insert_locations"
  on locations for insert
  with check (true);

create policy "anon_update_locations"
  on locations for update
  using (true);

-- pending_submissions: anyone can submit; anon can read/update (admin PIN gate is in the app)
create policy "anon_insert_submissions"
  on pending_submissions for insert
  with check (true);

create policy "anon_read_submissions"
  on pending_submissions for select
  using (true);

create policy "anon_update_submissions"
  on pending_submissions for update
  using (true);
