-- ─────────────────────────────────────────────
-- HaMakom — Supabase schema
-- Idempotent: safe to run multiple times
-- ─────────────────────────────────────────────

-- ── Tables ────────────────────────────────────

create table if not exists locations (
  id          bigint generated by default as identity primary key,
  name        text not null,
  name_he     text,
  city        text not null,
  city_he     text,
  category    text not null,
  occasion    text[]    default '{}',
  price       int       default 2,
  date_stage  int[]     default '{}',
  description text,
  description_he text,
  maps_query  text,
  kashrus     text,
  featured    boolean   default false,
  status      text      default 'approved',
  slug        text,
  region      text,
  needs_verification boolean default false,
  image_url   text,
  created_at  timestamptz default now()
);

create table if not exists pending_submissions (
  id           bigint generated by default as identity primary key,
  name         text not null,
  city         text not null,
  category     text not null,
  kashrus      text,
  why          text,
  whatsapp     text,
  date_stage   int[],
  price        int  default 2,
  status       text default 'pending',
  submitted_at timestamptz default now()
);

create table if not exists user_quiz_results (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references auth.users(id) on delete cascade,
  answers    jsonb not null,
  created_at timestamptz default now()
);

-- ── Row-Level Security ────────────────────────

alter table locations           enable row level security;
alter table pending_submissions  enable row level security;
alter table user_quiz_results    enable row level security;

-- locations
drop policy if exists "public_read_approved"      on locations;
drop policy if exists "admin_read_all_locations"   on locations;
drop policy if exists "admin_insert_locations"     on locations;
drop policy if exists "admin_update_locations"     on locations;
drop policy if exists "admin_delete_locations"     on locations;
-- legacy permissive policies (removed in security audit)
drop policy if exists "anon_insert_locations"      on locations;
drop policy if exists "anon_update_locations"      on locations;

create policy "public_read_approved"
  on locations for select
  using (status = 'approved');

create policy "admin_read_all_locations"
  on locations for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_insert_locations"
  on locations for insert
  to authenticated
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_update_locations"
  on locations for update
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_delete_locations"
  on locations for delete
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- pending_submissions
drop policy if exists "anon_insert_submissions"  on pending_submissions;
drop policy if exists "admin_read_submissions"   on pending_submissions;
drop policy if exists "admin_update_submissions" on pending_submissions;
-- legacy
drop policy if exists "anon_read_submissions"    on pending_submissions;
drop policy if exists "anon_update_submissions"  on pending_submissions;

create policy "anon_insert_submissions"
  on pending_submissions for insert
  with check (true);

create policy "admin_read_submissions"
  on pending_submissions for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_update_submissions"
  on pending_submissions for update
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- user_quiz_results
drop policy if exists "users_own_quiz_results" on user_quiz_results;

create policy "users_own_quiz_results"
  on user_quiz_results for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ── Analytics & Feedback Tables ───────────────

create table if not exists analytics_events (
  id          uuid primary key default gen_random_uuid(),
  session_id  text,
  user_id     uuid references auth.users(id) on delete set null,
  event_name  text not null,
  item_type   text,
  item_id     text,
  properties  jsonb default '{}',
  created_at  timestamptz default now()
);

alter table analytics_events enable row level security;

drop policy if exists "anon_insert_events" on analytics_events;
drop policy if exists "admin_read_events"  on analytics_events;

create policy "anon_insert_events"
  on analytics_events for insert
  with check (true);

create policy "admin_read_events"
  on analytics_events for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- ──────────────────────────────────────────────

create table if not exists recommendation_impressions (
  id                  uuid primary key default gen_random_uuid(),
  session_id          text,
  user_id             uuid references auth.users(id) on delete set null,
  quiz_answers        jsonb,
  primary_plan_id     text,
  backup_location_ids text[],
  created_at          timestamptz default now()
);

alter table recommendation_impressions enable row level security;

drop policy if exists "anon_insert_impressions" on recommendation_impressions;
drop policy if exists "admin_read_impressions"  on recommendation_impressions;

create policy "anon_insert_impressions"
  on recommendation_impressions for insert
  with check (true);

create policy "admin_read_impressions"
  on recommendation_impressions for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- ──────────────────────────────────────────────

create table if not exists recommendation_outcomes (
  id                             uuid primary key default gen_random_uuid(),
  recommendation_impression_id   uuid references recommendation_impressions(id) on delete cascade,
  saved                          boolean default false,
  shared                         boolean default false,
  maps_opened                    boolean default false,
  reminder_set                   boolean default false,
  went                           boolean,
  rating                         int,
  would_do_again                 boolean,
  updated_at                     timestamptz default now()
);

alter table recommendation_outcomes enable row level security;

drop policy if exists "anon_upsert_outcomes" on recommendation_outcomes;

create policy "anon_upsert_outcomes"
  on recommendation_outcomes for all
  with check (true);

-- ──────────────────────────────────────────────

create table if not exists user_feedback (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid references auth.users(id) on delete set null,
  item_type      text,
  item_id        text,
  went           boolean,
  rating         int,
  would_do_again boolean,
  notes          text,
  updated_at     timestamptz default now()
);

alter table user_feedback enable row level security;

drop policy if exists "users_own_feedback"  on user_feedback;
drop policy if exists "admin_read_feedback" on user_feedback;

create policy "users_own_feedback"
  on user_feedback for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "admin_read_feedback"
  on user_feedback for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- ── Admin Audit Log ────────────────────────────

create table if not exists admin_audit_log (
  id            uuid primary key default gen_random_uuid(),
  admin_user_id uuid references auth.users(id) on delete set null,
  action        text not null,
  target_table  text,
  target_id     text,
  old_value     jsonb,
  new_value     jsonb,
  created_at    timestamptz default now()
);

alter table admin_audit_log enable row level security;

drop policy if exists "admin_insert_audit" on admin_audit_log;
drop policy if exists "admin_read_audit"   on admin_audit_log;

create policy "admin_insert_audit"
  on admin_audit_log for insert
  to authenticated
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_read_audit"
  on admin_audit_log for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- ── Indexes ────────────────────────────────────

create index if not exists idx_locations_status      on locations(status);
create index if not exists idx_locations_status_city on locations(status, city);
create index if not exists idx_locations_category    on locations(category);
create index if not exists idx_locations_featured    on locations(featured) where featured = true;
create index if not exists idx_locations_occasions   on locations using gin(occasion);
create index if not exists idx_locations_date_stage  on locations using gin(date_stage);
create unique index if not exists idx_locations_slug on locations(slug) where slug is not null;

create index if not exists idx_analytics_session on analytics_events(session_id);
create index if not exists idx_analytics_created on analytics_events(created_at desc);
create index if not exists idx_analytics_event   on analytics_events(event_name);

create index if not exists idx_impressions_session on recommendation_impressions(session_id);
create index if not exists idx_impressions_created on recommendation_impressions(created_at desc);

-- ── Cloud Save Sync ────────────────────────────

create table if not exists saved_plans (
  id       uuid primary key default gen_random_uuid(),
  user_id  uuid references auth.users(id) on delete cascade not null,
  plan_id  text not null,
  saved_at timestamptz default now(),
  unique(user_id, plan_id)
);

alter table saved_plans enable row level security;

drop policy if exists "users_own_saved_plans" on saved_plans;

create policy "users_own_saved_plans" on saved_plans for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists saved_places (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references auth.users(id) on delete cascade not null,
  location_id bigint references locations(id) on delete cascade not null,
  saved_at    timestamptz default now(),
  unique(user_id, location_id)
);

alter table saved_places enable row level security;

drop policy if exists "users_own_saved_places" on saved_places;

create policy "users_own_saved_places" on saved_places for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── User Preferences ───────────────────────────

create table if not exists user_preferences (
  user_id    uuid references auth.users(id) on delete cascade primary key,
  lang       text default 'en',
  last_city  text,
  updated_at timestamptz default now()
);

alter table user_preferences enable row level security;

drop policy if exists "users_own_preferences" on user_preferences;

create policy "users_own_preferences" on user_preferences for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── Subscription Foundation ────────────────────

create table if not exists user_subscriptions (
  id                     uuid primary key default gen_random_uuid(),
  user_id                uuid references auth.users(id) on delete cascade unique,
  tier                   text default 'free',
  stripe_customer_id     text,
  stripe_subscription_id text,
  current_period_end     timestamptz,
  created_at             timestamptz default now()
);

alter table user_subscriptions enable row level security;

drop policy if exists "users_own_subscription" on user_subscriptions;

create policy "users_own_subscription" on user_subscriptions for select
  using (auth.uid() = user_id);

-- ── Problem Reports / Feedback ────────────────

create table if not exists problem_reports (
  id            uuid primary key default gen_random_uuid(),
  type          text not null,
  message       text,
  email         text,
  location_id   bigint references locations(id) on delete set null,
  location_name text,
  resolved      boolean default false,
  created_at    timestamptz default now()
);

alter table problem_reports enable row level security;

drop policy if exists "anon_insert_reports" on problem_reports;
drop policy if exists "admin_read_reports"  on problem_reports;
drop policy if exists "admin_update_reports" on problem_reports;

create policy "anon_insert_reports"
  on problem_reports for insert
  with check (true);

create policy "admin_read_reports"
  on problem_reports for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "admin_update_reports"
  on problem_reports for update
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Telegram notification on new report (via pg_net → notify-report Edge Function).
-- Requires WEBHOOK_SECRET to match the value stored in the function's env.
create extension if not exists pg_net with schema extensions;

create or replace function public.notify_problem_report()
returns trigger
language plpgsql
security definer
set search_path = public, net
as $$
declare
  fn_url text := 'https://kyenbpkgxnjrknebbiyr.supabase.co/functions/v1/notify-report';
  webhook_secret text := 'hmk_8f3e2a9c4b1d7e6f0a2c5b8d3e7f1a4c9b6d2e5f8a1c4b7d';
begin
  perform net.http_post(
    url := fn_url,
    body := jsonb_build_object(
      'type', 'INSERT',
      'table', 'problem_reports',
      'schema', 'public',
      'record', to_jsonb(NEW)
    ),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-webhook-secret', webhook_secret
    ),
    timeout_milliseconds := 5000
  );
  return NEW;
end;
$$;

drop trigger if exists problem_reports_notify on problem_reports;
create trigger problem_reports_notify
  after insert on problem_reports
  for each row execute function public.notify_problem_report();

-- ── Analytics Views ────────────────────────────

create or replace view analytics_summary as
select
  event_name,
  count(*)                      as total,
  count(distinct session_id)    as unique_sessions,
  date_trunc('day', created_at) as day
from analytics_events
group by event_name, date_trunc('day', created_at)
order by day desc, total desc;

create or replace view plan_popularity as
select
  item_id                                                   as plan_id,
  count(*) filter (where event_name = 'plan_saved')         as saves,
  count(*) filter (where event_name = 'plan_shared')        as shares,
  count(*) filter (where event_name = 'plan_maps_opened')   as maps_opens,
  count(distinct session_id)                                as unique_sessions
from analytics_events
where item_type = 'plan'
group by item_id
order by saves desc;

create or replace view location_popularity as
select
  item_id                                             as location_id,
  count(*) filter (where event_name = 'place_saved')  as saves,
  count(*) filter (where event_name = 'place_viewed') as views,
  count(distinct session_id)                          as unique_sessions
from analytics_events
where item_type = 'location'
group by item_id
order by saves desc;

-- ── Migrations (safe to run on existing DB) ────

do $$ begin
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='slug') then
    alter table locations add column slug text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='region') then
    alter table locations add column region text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='needs_verification') then
    alter table locations add column needs_verification boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='image_url') then
    alter table locations add column image_url text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='lat') then
    alter table locations add column lat double precision;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='lng') then
    alter table locations add column lng double precision;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='opening_hours') then
    alter table locations add column opening_hours jsonb;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='phone') then
    alter table locations add column phone text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='website') then
    alter table locations add column website text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='google_rating') then
    alter table locations add column google_rating numeric(2,1);
  end if;
  if not exists (select 1 from information_schema.columns where table_name='locations' and column_name='google_price_level') then
    alter table locations add column google_price_level int;
  end if;
end $$;

-- ── Community Reviews ──────────────────────────

create table if not exists location_reviews (
  id          uuid primary key default gen_random_uuid(),
  location_id bigint references locations(id) on delete cascade,
  user_id     uuid references auth.users(id) on delete cascade,
  rating      int not null check (rating >= 1 and rating <= 5),
  body        text check (char_length(body) <= 200),
  created_at  timestamptz default now(),
  unique (location_id, user_id)
);

alter table location_reviews enable row level security;
create policy "public_read_reviews"    on location_reviews for select using (true);
create policy "auth_insert_review"     on location_reviews for insert with check (auth.uid() = user_id);
create policy "auth_update_own_review" on location_reviews for update using (auth.uid() = user_id);

-- Trigger: keep avg_rating + review_count on locations in sync
create or replace function sync_location_rating() returns trigger
language plpgsql security definer as $$
declare target bigint;
begin
  target := coalesce(new.location_id, old.location_id);
  update locations
    set avg_rating   = (select round(avg(rating)::numeric, 1) from location_reviews where location_id = target),
        review_count = (select count(*) from location_reviews where location_id = target)
    where id = target;
  return coalesce(new, old);
end;
$$;

drop trigger if exists location_rating_sync on location_reviews;
create trigger location_rating_sync
  after insert or update or delete on location_reviews
  for each row execute function sync_location_rating();
