-- ============================================================================
-- HaMakom core schema
-- Everything the app reads/writes, in one migration. Idempotent (IF NOT EXISTS)
-- so it can run against a fresh project or one with a partial schema.
--
-- Apply: supabase db push  (or paste into the SQL editor)
-- Then import locations:   node scripts/sync-locations-to-supabase.mjs
-- ============================================================================

-- ── locations ───────────────────────────────────────────────────────────────
create table if not exists public.locations (
  id             bigint generated by default as identity primary key,
  name           text not null,
  name_he        text,
  city           text not null,
  city_he        text,
  category       text not null,
  occasion       text[] default '{}',
  price          smallint check (price between 1 and 4),
  date_stage     smallint[] default '{1}',
  description    text,
  description_he text,
  maps_query     text,
  kashrus        text,
  featured       boolean default false,
  status         text not null default 'pending' check (status in ('pending','approved','rejected')),
  image_url      text,
  rating         smallint check (rating between 1 and 5),
  hidden_gem     boolean default false,
  notes          text,
  lat            double precision,
  lng            double precision,
  is_partner     boolean default false,
  partner_tier   text,
  created_at     timestamptz default now()
);

-- Columns that may be missing on an older locations table
alter table public.locations add column if not exists rating smallint;
alter table public.locations add column if not exists hidden_gem boolean default false;
alter table public.locations add column if not exists notes text;
alter table public.locations add column if not exists lat double precision;
alter table public.locations add column if not exists lng double precision;
alter table public.locations add column if not exists is_partner boolean default false;
alter table public.locations add column if not exists partner_tier text;
alter table public.locations add column if not exists reservation_url text;
alter table public.locations add column if not exists partner_contact text;

create index if not exists locations_status_idx on public.locations (status);
create index if not exists locations_city_idx on public.locations (city);

-- ── suggest-a-place queue ───────────────────────────────────────────────────
create table if not exists public.pending_submissions (
  id         bigint generated by default as identity primary key,
  name       text not null,
  city       text,
  category   text,
  kashrus    text,
  why        text,
  whatsapp   text,
  date_stage smallint[],
  price      smallint,
  maps_query text,
  occasion   text[],
  status     text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz default now()
);

-- ── saved items (signed-in sync) ────────────────────────────────────────────
create table if not exists public.saved_plans (
  user_id    uuid not null references auth.users (id) on delete cascade,
  plan_id    text not null,
  created_at timestamptz default now(),
  primary key (user_id, plan_id)
);

create table if not exists public.saved_places (
  user_id     uuid not null references auth.users (id) on delete cascade,
  location_id bigint not null,
  created_at  timestamptz default now(),
  primary key (user_id, location_id)
);

-- ── analytics ───────────────────────────────────────────────────────────────
create table if not exists public.analytics_events (
  id         bigint generated by default as identity primary key,
  session_id text,
  user_id    uuid,
  event_name text not null,
  item_type  text,
  item_id    text,
  properties jsonb default '{}',
  created_at timestamptz default now()
);

create table if not exists public.recommendation_impressions (
  id                  bigint generated by default as identity primary key,
  session_id          text,
  user_id             uuid,
  quiz_answers        jsonb default '{}',
  primary_plan_id     text,
  backup_location_ids jsonb default '[]',
  created_at          timestamptz default now()
);

create table if not exists public.recommendation_outcomes (
  recommendation_impression_id bigint primary key
    references public.recommendation_impressions (id) on delete cascade,
  saved       boolean,
  shared      boolean,
  maps_opened boolean,
  backups_opened boolean,
  updated_at  timestamptz default now()
);

create table if not exists public.user_feedback (
  user_id       uuid not null,
  item_type     text not null,
  item_id       text not null,
  went          boolean,
  rating        smallint,
  would_do_again boolean,
  notes         text,
  updated_at    timestamptz default now(),
  primary key (user_id, item_type, item_id)
);

-- ── reviews (per-location, per-user) ───────────────────────────────────────
create table if not exists public.location_reviews (
  id          bigint generated by default as identity primary key,
  location_id bigint not null,
  user_id     uuid not null,
  rating      smallint check (rating between 1 and 5),
  body        text,
  created_at  timestamptz default now(),
  unique (location_id, user_id)
);

-- ── problem reports (feedback modal) ────────────────────────────────────────
create table if not exists public.problem_reports (
  id            bigint generated by default as identity primary key,
  type          text,
  message       text,
  email         text,
  location_id   bigint,
  location_name text,
  created_at    timestamptz default now()
);

-- ── partner inquiries (For Businesses page) ────────────────────────────────
create table if not exists public.partner_inquiries (
  id            bigint generated by default as identity primary key,
  business_name text not null,
  contact_name  text,
  phone         text,
  email         text,
  message       text,
  lang          text,
  status        text not null default 'new' check (status in ('new','contacted','converted','closed')),
  created_at    timestamptz default now()
);

-- ============================================================================
-- Row Level Security
-- ============================================================================
alter table public.locations                  enable row level security;
alter table public.pending_submissions        enable row level security;
alter table public.saved_plans                enable row level security;
alter table public.saved_places               enable row level security;
alter table public.analytics_events           enable row level security;
alter table public.recommendation_impressions enable row level security;
alter table public.recommendation_outcomes    enable row level security;
alter table public.user_feedback              enable row level security;
alter table public.location_reviews           enable row level security;
alter table public.problem_reports            enable row level security;
alter table public.partner_inquiries          enable row level security;

-- admin = auth user whose app_metadata.role is 'admin' (matches isAdminUser in the app)
create or replace function public.is_admin() returns boolean
language sql stable as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false)
$$;

-- locations: anyone reads approved; admins read/write everything
drop policy if exists locations_public_read on public.locations;
create policy locations_public_read on public.locations
  for select using (status = 'approved' or public.is_admin());
drop policy if exists locations_admin_write on public.locations;
create policy locations_admin_write on public.locations
  for all using (public.is_admin()) with check (public.is_admin());

-- pending submissions: anyone can suggest; only admins see/manage the queue
drop policy if exists pending_public_insert on public.pending_submissions;
create policy pending_public_insert on public.pending_submissions
  for insert with check (status = 'pending');
drop policy if exists pending_admin_all on public.pending_submissions;
create policy pending_admin_all on public.pending_submissions
  for all using (public.is_admin()) with check (public.is_admin());

-- saved items: owners only
drop policy if exists saved_plans_owner on public.saved_plans;
create policy saved_plans_owner on public.saved_plans
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists saved_places_owner on public.saved_places;
create policy saved_places_owner on public.saved_places
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- analytics: insert-only from clients (consent enforced app-side); admins read
drop policy if exists analytics_public_insert on public.analytics_events;
create policy analytics_public_insert on public.analytics_events
  for insert with check (true);
drop policy if exists analytics_admin_read on public.analytics_events;
create policy analytics_admin_read on public.analytics_events
  for select using (public.is_admin());

drop policy if exists impressions_public_insert on public.recommendation_impressions;
create policy impressions_public_insert on public.recommendation_impressions
  for insert with check (true);
drop policy if exists impressions_public_read on public.recommendation_impressions;
create policy impressions_public_read on public.recommendation_impressions
  for select using (true);

drop policy if exists outcomes_public_upsert on public.recommendation_outcomes;
create policy outcomes_public_upsert on public.recommendation_outcomes
  for all using (true) with check (true);

-- user feedback / reviews: owners write their own; reviews are publicly readable
drop policy if exists feedback_owner on public.user_feedback;
create policy feedback_owner on public.user_feedback
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists reviews_public_read on public.location_reviews;
create policy reviews_public_read on public.location_reviews
  for select using (true);
drop policy if exists reviews_owner_write on public.location_reviews;
create policy reviews_owner_write on public.location_reviews
  for insert with check (auth.uid() = user_id);
drop policy if exists reviews_owner_update on public.location_reviews;
create policy reviews_owner_update on public.location_reviews
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- problem reports & partner inquiries: anyone can submit, only admins read
drop policy if exists reports_public_insert on public.problem_reports;
create policy reports_public_insert on public.problem_reports
  for insert with check (true);
drop policy if exists reports_admin_read on public.problem_reports;
create policy reports_admin_read on public.problem_reports
  for select using (public.is_admin());

drop policy if exists partner_public_insert on public.partner_inquiries;
create policy partner_public_insert on public.partner_inquiries
  for insert with check (status = 'new');
drop policy if exists partner_admin_all on public.partner_inquiries;
create policy partner_admin_all on public.partner_inquiries
  for all using (public.is_admin()) with check (public.is_admin());
